FROM php:8.2-apache

WORKDIR /var/www/html
COPY . /var/www/html/

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends libpq-dev; \
    docker-php-ext-install pdo_pgsql; \
    rm -rf /var/lib/apt/lists/*

EXPOSE 80
